# Generated by Django 4.1.6 on 2023-02-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_department', models.CharField(choices=[('Nephrology', 'Nephrology'), ('Infertility', 'Infertility'), ('Anesthesiology', 'Anesthesiology'), ('General Surgery', 'General Surgery'), ('General Medicine', 'General Medicine'), ('Dermatology', 'Dermatology'), ('Psychiatry', 'Psychiatry'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Dental', 'Dental'), ('Otolaryngologist', 'Otolaryngologist'), ('Ophthalmology', 'Ophthalmology'), ('Paediatrics', 'Paediatrics'), ('Obstetrics', 'Obstetrics'), ('Gynaecology', 'Gynaecology')], max_length=255)),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booking_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
            ],
        ),
    ]
