# Generated by Django 4.1.6 on 2023-02-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='p_department',
        ),
    ]
