# Generated by Django 4.1.6 on 2023-02-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_booking_p_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_on',
            new_name='booked_on',
        ),
    ]
